### ISSUE TITLE
ModuleNotFoundError: No module named 'redis'

### ISSUE THREAD

**Issue by wityat** [rodion-gudz/telegram-bot-template#48]
Lol not working. Saying that no redis installed, but aioredis already installed

Traceback (most recent call last):
  File "C:\Users\Витя Кенг\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Витя Кенг\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\seller-kit-refractor\app\__main__.py", line 10, in <module>
    from aiogram.dispatcher.fsm.storage.redis import DefaultKeyBuilder, RedisStorage
  File "D:\seller-kit-refractor\venv\lib\site-packages\aiogram\dispatcher\fsm\storage\redis.py", line 5, in <module>
    from redis.asyncio.client import Redis

**Comment by wityat** [comment]
There are all requirements installed on python3.10. Set token and no more changes.

**Comment by wityat** [comment]
redis==4.3.4

add this to requirements and maybe delete aioredis idk

**Comment by wityat** [comment]
Yeas, change aioredis to redis due to https://docs.aiogram.dev/en/dev-3.x/changelog.html
![image](https://user-images.githubusercontent.com/33394513/177172495-39d49514-96b4-44cd-8267-be01bf53fb40.png)

**Comment by rodion-gudz** [comment]
✅ [fixed](https://github.com/rodion-gudz/telegram-bot-template/commit/89808c5320e21ba27d2d76c6a77dc05bad4f6e8e)
